/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
  }
}
